controller_manager:
  ros_parameters:
    update_rate: 100 = Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint trajectory_controller:
  ros_parameters:
    joints:
      - front_right_axel_joint
      - front_right_wheel_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity