controller_manager:
  ros__parameters:
    update_rate: 100  # Hz

    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController

    diff_drive_controller: 
      type: diff_drive_controller/DiffDriveController

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

joint_trajectory_controller:
  ros__parameters:
    joints:
      - front_left_axel_joint
      - front_right_axel_joint
    interface_name: position
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    gains:
      front_left_axel_joint.p: 0.0
      front_left_axel_joint.i: 0.0
      front_left_axel_joint.d: 0.0
      front_right_axel_joint.p: 0.0
      front_right_axel_joint.i: 0.0
      front_right_axel_joint.d: 0.0 

diff_drive_controller:
  ros__parameters: 
    publish_rate: 50.0
    base_frame_id: base_link
    left_wheel_names: ['rear_left_wheel_joint']
    right_wheel_names: ['rear_right_wheel_joint']
    wheel_separation: 0.2202
    wheel_radius: 0.04
    use_stamped_vel: false
